---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-rabbitmq-configs-prod
  namespace: ladesa-ro-production
spec:
  hostAPI: https://infisical.ladesa.com.br/api
  resyncInterval: 10
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
      secretsScope:
        projectSlug: rabbitmq-4sh-s
        envSlug: prod
        secretsPath: /
        recursive: false
  managedSecretReference:
    secretName: ladesa-ro-rabbitmq-config
    secretNamespace: ladesa-ro-production
    secretType: Opaque
    creationPolicy: Orphan
