apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-mnesia-pvc
  namespace: ladesa-ro-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
