---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-image-updater-webhook
  namespace: image-updater
  labels:
    app.kubernetes.io/name: image-updater
spec:
  hostAPI: https://infisical.ladesa.com.br/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
      secretsScope:
        projectSlug: "foundation-image-updater-w0cw"
        envSlug: prod
        secretsPath: /
        recursive: true
  managedSecretReference:
    secretName: argocd-image-updater-secret
    secretNamespace: image-updater
    secretType: Opaque
    creationPolicy: Owner
