---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: dados
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:18.0-standard-trixie@sha256:e56be4982b17aa701b1263dbfc2fa95741177bbd3fe55d487a981e134d08625c

  storage:
    storageClass: local-path
    size: 1Gi

  superuserSecret:
    name: postgres-superuser-bootstrap

  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - api-dev-v1
          - api-dev-v2
          - infisical
          - sso-production
          - management-service-v3
        roles:
          - ladesa
          - infisical
          - api-dev
          - sso-production
        source:
          externalCluster: db-postgres-antigo

  externalClusters:
    - name: db-postgres-antigo
      connectionParameters:
        host: db-postgres.dados.svc.cluster.local
        port: "5432"
        user: ladesa
        dbname: postgres
      password:
        name: pg-env
        key: POSTGRES_PASSWORD

  managed:
    roles:
      - name: ladesa
        ensure: present
        login: true
        inherit: true
        passwordSecret:
          name: postgres-ladesa-rotated
      - name: infisical
        ensure: present
        login: true
        inherit: true
      - name: api-dev
        ensure: present
        login: true
        inherit: true
      - name: sso-production
        ensure: present
        login: true
        inherit: true

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: api-dev-v1
  namespace: dados
spec:
  cluster:
    name: postgres
  name: api-dev-v1
  owner: api-dev
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: api-dev-v2
  namespace: dados
spec:
  cluster:
    name: postgres
  name: api-dev-v2
  owner: api-dev
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: infisical
  namespace: dados
spec:
  cluster:
    name: postgres
  name: infisical
  owner: infisical
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sso-production
  namespace: dados
spec:
  cluster:
    name: postgres
  name: sso-production
  owner: sso-production
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: management-service-v3
  namespace: dados
spec:
  cluster:
    name: postgres
  name: management-service-v3
  owner: api-dev
  databaseReclaimPolicy: retain
---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres
  namespace: dados
spec:
  type: ClusterIP
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
  ports:
    - port: 5432
      targetPort: 5432
