---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundation-infisical
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: ladesa
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: infisical-standalone
    targetRevision: 1.4.0
    helm:
      releaseName: infisical
      values: |
        fullnameOverride: infisical
        nameOverride: infisical
        infisical:
          enabled: true
          fullnameOverride: ""
          name: infisical
          autoDatabaseSchemaMigration: true
          kubeSecretRef: infisical-secrets
          replicaCount: 1
          image:
            repository: infisical/infisical
            tag: v0.99.0-postgres
            pullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 1536Mi
          service:
            type: ClusterIP
        postgresql:
          enabled: false
        redis:
          enabled: false
        ingress:
          enabled: true
          ingressClassName: traefik
          hostName: infisical.ladesa.com.br
          nginx:
            enabled: false
          annotations:
            cert-manager.io/cluster-issuer: ladesa-ro-issuer-production
          tls:
            - hosts:
                - infisical.ladesa.com.br
              secretName: infisical-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  revisionHistoryLimit: 3
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: infisical-infisical
      namespace: infisical
      jsonPointers:
        - /metadata/annotations/updatedAt
        - /spec/template/metadata/annotations/updatedAt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
