---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: dados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: adminer
          image: docker.io/adminer:latest
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: dados
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: adminer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer
  namespace: dados
  annotations:
    cert-manager.io/cluster-issuer: ladesa-ro-issuer-production
spec:
  ingressClassName: traefik
  rules:
    - host: adminer.ladesa.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adminer
                port:
                  number: 8080
  tls:
    - hosts:
        - adminer.ladesa.com.br
      secretName: adminer-tls
