apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-dados-minio-env
  namespace: dados
  labels:
    app.kubernetes.io/name: dados-configs
spec:
  hostAPI: https://infisical.ladesa.com.br/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
      secretsScope:
        projectSlug: "foundation-minio-z-hvh"
        envSlug: prod
        secretsPath: /
        recursive: true
  managedSecretReference:
    secretName: minio-env
    secretNamespace: dados
    secretType: Opaque
    creationPolicy: Owner
