apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
  namespace: dados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
      - name: db-postgres
        image: docker.io/postgres:18
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: pg-env
        volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql
          - name: backups
            mountPath: /backups
      volumes:
        - name: pgdata
          hostPath:
            path: /root/dados/vols/pgdata
            type: DirectoryOrCreate
        - name: backups
          hostPath:
            path: /root/dados/vols/backups/postgres
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres
  namespace: dados
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30989
  selector:
    app: db-postgres

