---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: dados
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  image: docker.io/mariadb:12@sha256:a02fe89cb597d4375812b2eac90cf9d0775d4686daa7f7cc750ebbcad7525bbc
  rootPasswordSecretKeyRef:
    name: mariadb-env
    key: MARIADB_ROOT_PASSWORD
  replicas: 1
  port: 3306
  storage:
    size: 1Gi
    storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: db-mariadb
  namespace: dados
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: mariadb
    k8s.mariadb.com/role: primary
  ports:
    - port: 3306
      targetPort: 3306
