---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-amqp
  namespace: ladesa-ro-production
spec:
  type: LoadBalancer
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
  selector:
    app.kubernetes.io/name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-web
  namespace: ladesa-ro-production
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: management
  selector:
    app.kubernetes.io/name: rabbitmq
