---
- name: Bootstrap do cluster ldsa
  hosts: all
  become: true
  roles:
    - role: k3s
      tags: [k3s]
    - role: firewalld
      tags: [firewalld]
    - role: vault_repo
      tags: [vault-repo]
    - role: argocd_bootstrap
      tags: [argocd-bootstrap]
    - role: self_pull_timer
      tags: [self-pull-timer]
