---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: ladesa-ro-production
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    rabbitmq.com/legacy-startup-probe: "true"
spec:
  replicas: {{ .Values.replicas }}
  image: {{ .Values.image }}
  persistence:
    storageClassName: {{ .Values.persistence.storageClassName }}
    storage: {{ .Values.persistence.storage }}
  rabbitmq:
    additionalConfig: |
      load_definitions = /etc/rabbitmq/definitions.json
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                volumeMounts:
                  - mountPath: /etc/rabbitmq/definitions.json
                    subPath: definitions.json
                    name: definitions
            volumes:
              - name: definitions
                secret:
                  secretName: rabbitmq-definitions
